
export const countries = [
    { name: "Afghanistan", code: "AF", flag: "🇦🇫", currency: "AFN", symbol: "؋" },
    { name: "Åland Islands", code: "AX", flag: "🇦🇽", currency: "EUR", symbol: "€" },
    { name: "Albania", code: "AL", flag: "🇦🇱", currency: "ALL", symbol: "Lek" },
    { name: "Algeria", code: "DZ", flag: "🇩🇿", currency: "DZD", symbol: "دج" },
    { name: "American Samoa", code: "AS", flag: "🇦🇸", currency: "USD", symbol: "$" },
    { name: "Andorra", code: "AD", flag: "🇦🇩", currency: "EUR", symbol: "€" },
    { name: "Angola", code: "AO", flag: "🇦🇴", currency: "AOA", symbol: "Kz" },
    { name: "Anguilla", code: "AI", flag: "🇦🇮", currency: "XCD", symbol: "$" },
    { name: "Antarctica", code: "AQ", flag: "🇦🇶", currency: "", symbol: "" },
    { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", currency: "XCD", symbol: "$" },
    { name: "Argentina", code: "AR", flag: "🇦🇷", currency: "ARS", symbol: "$" },
    { name: "Armenia", code: "AM", flag: "🇦🇲", currency: "AMD", symbol: "֏" },
    { name: "Aruba", code: "AW", flag: "🇦🇼", currency: "AWG", symbol: "ƒ" },
    { name: "Australia", code: "AU", flag: "🇦🇺", currency: "AUD", symbol: "$" },
    { name: "Austria", code: "AT", flag: "🇦🇹", currency: "EUR", symbol: "€" },
    { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", currency: "AZN", symbol: "₼" },
    { name: "Bahamas", code: "BS", flag: "🇧🇸", currency: "BSD", symbol: "$" },
    { name: "Bahrain", code: "BH", flag: "🇧🇭", currency: "BHD", symbol: ".د.ب" },
    { name: "Bangladesh", code: "BD", flag: "🇧🇩", currency: "BDT", symbol: "৳" },
    { name: "Barbados", code: "BB", flag: "🇧🇧", currency: "BBD", symbol: "$" },
    { name: "Belarus", code: "BY", flag: "🇧🇾", currency: "BYN", symbol: "Br" },
    { name: "Belgium", code: "BE", flag: "🇧🇪", currency: "EUR", symbol: "€" },
    { name: "Belize", code: "BZ", flag: "🇧🇿", currency: "BZD", symbol: "BZ$" },
    { name: "Benin", code: "BJ", flag: "🇧🇯", currency: "XOF", symbol: "CFA" },
    { name: "Bermuda", code: "BM", flag: "🇧🇲", currency: "BMD", symbol: "$" },
    { name: "Bhutan", code: "BT", flag: "🇧🇹", currency: "BTN", symbol: "Nu." },
    { name: "Bolivia", code: "BO", flag: "🇧🇴", currency: "BOB", symbol: "Bs." },
    { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", currency: "BAM", symbol: "KM" },
    { name: "Botswana", code: "BW", flag: "🇧🇼", currency: "BWP", symbol: "P" },
    { name: "Bouvet Island", code: "BV", flag: "🇧🇻", currency: "NOK", symbol: "kr" },
    { name: "Brazil", code: "BR", flag: "🇧🇷", currency: "BRL", symbol: "R$" },
    { name: "British Indian Ocean Territory", code: "IO", flag: "🇮🇴", currency: "USD", symbol: "$" },
    { name: "Brunei Darussalam", code: "BN", flag: "🇧🇳", currency: "BND", symbol: "$" },
    { name: "Bulgaria", code: "BG", flag: "🇧🇬", currency: "BGN", symbol: "лв" },
    { name: "Burkina Faso", code: "BF", flag: "🇧🇫", currency: "XOF", symbol: "CFA" },
    { name: "Burundi", code: "BI", flag: "🇧🇮", currency: "BIF", symbol: "FBu" },
    { name: "Cambodia", code: "KH", flag: "🇰🇭", currency: "KHR", symbol: "៛" },
    { name: "Cameroon", code: "CM", flag: "🇨🇲", currency: "XAF", symbol: "FCFA" },
    { name: "Canada", code: "CA", flag: "🇨🇦", currency: "CAD", symbol: "$" },
    { name: "Cape Verde", code: "CV", flag: "🇨🇻", currency: "CVE", symbol: "Esc" },
    { name: "Cayman Islands", code: "KY", flag: "🇰🇾", currency: "KYD", symbol: "$" },
    { name: "Central African Republic", code: "CF", flag: "🇨🇫", currency: "XAF", symbol: "FCFA" },
    { name: "Chad", code: "TD", flag: "🇹🇩", currency: "XAF", symbol: "FCFA" },
    { name: "Chile", code: "CL", flag: "🇨🇱", currency: "CLP", symbol: "$" },
    { name: "China", code: "CN", flag: "🇨🇳", currency: "CNY", symbol: "¥" },
    { name: "Christmas Island", code: "CX", flag: "🇨🇽", currency: "AUD", symbol: "$" },
    { name: "Cocos (Keeling) Islands", code: "CC", flag: "🇨🇨", currency: "AUD", symbol: "$" },
    { name: "Colombia", code: "CO", flag: "🇨🇴", currency: "COP", symbol: "$" },
    { name: "Comoros", code: "KM", flag: "🇰🇲", currency: "KMF", symbol: "CF" },
    { name: "Congo", code: "CG", flag: "🇨🇬", currency: "XAF", symbol: "FCFA" },
    { name: "Congo, The Democratic Republic of the", code: "CD", flag: "🇨🇩", currency: "CDF", symbol: "FC" },
    { name: "Cook Islands", code: "CK", flag: "🇨🇰", currency: "NZD", symbol: "$" },
    { name: "Costa Rica", code: "CR", flag: "🇨🇷", currency: "CRC", symbol: "₡" },
    { name: "Cote D'Ivoire", code: "CI", flag: "🇨🇮", currency: "XOF", symbol: "CFA" },
    { name: "Croatia", code: "HR", flag: "🇭🇷", currency: "EUR", symbol: "€" },
    { name: "Cuba", code: "CU", flag: "🇨🇺", currency: "CUP", symbol: "₱" },
    { name: "Cyprus", code: "CY", flag: "🇨🇾", currency: "EUR", symbol: "€" },
    { name: "Czech Republic", code: "CZ", flag: "🇨🇿", currency: "CZK", symbol: "Kč" },
    { name: "Denmark", code: "DK", flag: "🇩🇰", currency: "DKK", symbol: "kr" },
    { name: "Djibouti", code: "DJ", flag: "🇩🇯", currency: "DJF", symbol: "Fdj" },
    { name: "Dominica", code: "DM", flag: "🇩🇲", currency: "XCD", symbol: "$" },
    { name: "Dominican Republic", code: "DO", flag: "🇩🇴", currency: "DOP", symbol: "RD$" },
    { name: "Ecuador", code: "EC", flag: "🇪🇨", currency: "USD", symbol: "$" },
    { name: "Egypt", code: "EG", flag: "🇪🇬", currency: "EGP", symbol: "£" },
    { name: "El Salvador", code: "SV", flag: "🇸🇻", currency: "USD", symbol: "$" },
    { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", currency: "XAF", symbol: "FCFA" },
    { name: "Eritrea", code: "ER", flag: "🇪🇷", currency: "ERN", symbol: "Nfk" },
    { name: "Estonia", code: "EE", flag: "🇪🇪", currency: "EUR", symbol: "€" },
    { name: "Ethiopia", code: "ET", flag: "🇪🇹", currency: "ETB", symbol: "Br" },
    { name: "Falkland Islands (Malvinas)", code: "FK", flag: "🇫🇰", currency: "FKP", symbol: "£" },
    { name: "Faroe Islands", code: "FO", flag: "🇫🇴", currency: "DKK", symbol: "kr" },
    { name: "Fiji", code: "FJ", flag: "🇫🇯", currency: "FJD", symbol: "$" },
    { name: "Finland", code: "FI", flag: "🇫🇮", currency: "EUR", symbol: "€" },
    { name: "France", code: "FR", flag: "🇫🇷", currency: "EUR", symbol: "€" },
    { name: "French Guiana", code: "GF", flag: "🇬🇫", currency: "EUR", symbol: "€" },
    { name: "French Polynesia", code: "PF", flag: "🇵🇫", currency: "XPF", symbol: "₣" },
    { name: "French Southern Territories", code: "TF", flag: "🇹🇫", currency: "EUR", symbol: "€" },
    { name: "Gabon", code: "GA", flag: "🇬🇦", currency: "XAF", symbol: "FCFA" },
    { name: "Gambia", code: "GM", flag: "🇬🇲", currency: "GMD", symbol: "D" },
    { name: "Georgia", code: "GE", flag: "🇬🇪", currency: "GEL", symbol: "₾" },
    { name: "Germany", code: "DE", flag: "🇩🇪", currency: "EUR", symbol: "€" },
    { name: "Ghana", code: "GH", flag: "🇬🇭", currency: "GHS", symbol: "GH₵" },
    { name: "Gibraltar", code: "GI", flag: "🇬🇮", currency: "GIP", symbol: "£" },
    { name: "Greece", code: "GR", flag: "🇬🇷", currency: "EUR", symbol: "€" },
    { name: "Greenland", code: "GL", flag: "🇬🇱", currency: "DKK", symbol: "kr" },
    { name: "Grenada", code: "GD", flag: "🇬🇩", currency: "XCD", symbol: "$" },
    { name: "Guadeloupe", code: "GP", flag: "🇬🇵", currency: "EUR", symbol: "€" },
    { name: "Guam", code: "GU", flag: "🇬🇺", currency: "USD", symbol: "$" },
    { name: "Guatemala", code: "GT", flag: "🇬🇹", currency: "GTQ", symbol: "Q" },
    { name: "Guernsey", code: "GG", flag: "🇬🇬", currency: "GBP", symbol: "£" },
    { name: "Guinea", code: "GN", flag: "🇬🇳", currency: "GNF", symbol: "FG" },
    { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", currency: "XOF", symbol: "CFA" },
    { name: "Guyana", code: "GY", flag: "🇬🇾", currency: "GYD", symbol: "$" },
    { name: "Haiti", code: "HT", flag: "🇭🇹", currency: "HTG", symbol: "G" },
    { name: "Heard Island and Mcdonald Islands", code: "HM", flag: "🇭🇲", currency: "AUD", symbol: "$" },
    { name: "Holy See (Vatican City State)", code: "VA", flag: "🇻🇦", currency: "EUR", symbol: "€" },
    { name: "Honduras", code: "HN", flag: "🇭🇳", currency: "HNL", symbol: "L" },
    { name: "Hong Kong", code: "HK", flag: "🇭🇰", currency: "HKD", symbol: "$" },
    { name: "Hungary", code: "HU", flag: "🇭🇺", currency: "HUF", symbol: "Ft" },
    { name: "Iceland", code: "IS", flag: "🇮🇸", currency: "ISK", symbol: "kr" },
    { name: "India", code: "IN", flag: "🇮🇳", currency: "INR", symbol: "₹" },
    { name: "Indonesia", code: "ID", flag: "🇮🇩", currency: "IDR", symbol: "Rp" },
    { name: "Iran, Islamic Republic Of", code: "IR", flag: "🇮🇷", currency: "IRR", symbol: "﷼" },
    { name: "Iraq", code: "IQ", flag: "🇮🇶", currency: "IQD", symbol: "ع.د" },
    { name: "Ireland", code: "IE", flag: "🇮🇪", currency: "EUR", symbol: "€" },
    { name: "Isle of Man", code: "IM", flag: "🇮🇲", currency: "GBP", symbol: "£" },
    { name: "Israel", code: "IL", flag: "🇮🇱", currency: "ILS", symbol: "₪" },
    { name: "Italy", code: "IT", flag: "🇮🇹", currency: "EUR", symbol: "€" },
    { name: "Jamaica", code: "JM", flag: "🇯🇲", currency: "JMD", symbol: "J$" },
    { name: "Japan", code: "JP", flag: "🇯🇵", currency: "JPY", symbol: "¥" },
    { name: "Jersey", code: "JE", flag: "🇯🇪", currency: "GBP", symbol: "£" },
    { name: "Jordan", code: "JO", flag: "🇯🇴", currency: "JOD", symbol: "JD" },
    { name: "Kazakhstan", code: "KZ", flag: "🇰🇿", currency: "KZT", symbol: "₸" },
    { name: "Kenya", code: "KE", flag: "🇰🇪", currency: "KES", symbol: "KSh" },
    { name: "Kiribati", code: "KI", flag: "🇰🇮", currency: "AUD", symbol: "$" },
    { name: "Korea, Democratic People's Republic of", code: "KP", flag: "🇰🇵", currency: "KPW", symbol: "₩" },
    { name: "Korea, Republic of", code: "KR", flag: "🇰🇷", currency: "KRW", symbol: "₩" },
    { name: "Kuwait", code: "KW", flag: "🇰🇼", currency: "KWD", symbol: "KD" },
    { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", currency: "KGS", symbol: "лв" },
    { name: "Lao People's Democratic Republic", code: "LA", flag: "🇱🇦", currency: "LAK", symbol: "₭" },
    { name: "Latvia", code: "LV", flag: "🇱🇻", currency: "EUR", symbol: "€" },
    { name: "Lebanon", code: "LB", flag: "🇱🇧", currency: "LBP", symbol: "£" },
    { name: "Lesotho", code: "LS", flag: "🇱🇸", currency: "LSL", symbol: "L" },
    { name: "Liberia", code: "LR", flag: "🇱🇷", currency: "LRD", symbol: "$" },
    { name: "Libyan Arab Jamahiriya", code: "LY", flag: "🇱🇾", currency: "LYD", symbol: "LD" },
    { name: "Liechtenstein", code: "LI", flag: "🇱🇮", currency: "CHF", symbol: "CHF" },
    { name: "Lithuania", code: "LT", flag: "🇱🇹", currency: "EUR", symbol: "€" },
    { name: "Luxembourg", code: "LU", flag: "🇱🇺", currency: "EUR", symbol: "€" },
    { name: "Macao", code: "MO", flag: "🇲🇴", currency: "MOP", symbol: "MOP$" },
    { name: "Macedonia, The Former Yugoslav Republic of", code: "MK", flag: "🇲🇰", currency: "MKD", symbol: "ден" },
    { name: "Madagascar", code: "MG", flag: "🇲🇬", currency: "MGA", symbol: "Ar" },
    { name: "Malawi", code: "MW", flag: "🇲🇼", currency: "MWK", symbol: "MK" },
    { name: "Malaysia", code: "MY", flag: "🇲🇾", currency: "MYR", symbol: "RM" },
    { name: "Maldives", code: "MV", flag: "🇲🇻", currency: "MVR", symbol: "Rf" },
    { name: "Mali", code: "ML", flag: "🇲🇱", currency: "XOF", symbol: "CFA" },
    { name: "Malta", code: "MT", flag: "🇲🇹", currency: "EUR", symbol: "€" },
    { name: "Marshall Islands", code: "MH", flag: "🇲🇭", currency: "USD", symbol: "$" },
    { name: "Martinique", code: "MQ", flag: "🇲🇶", currency: "EUR", symbol: "€" },
    { name: "Mauritania", code: "MR", flag: "🇲🇷", currency: "MRO", symbol: "UM" },
    { name: "Mauritius", code: "MU", flag: "🇲🇺", currency: "MUR", symbol: "₨" },
    { name: "Mayotte", code: "YT", flag: "🇾🇹", currency: "EUR", symbol: "€" },
    { name: "Mexico", code: "MX", flag: "🇲🇽", currency: "MXN", symbol: "$" },
    { name: "Micronesia, Federated States of", code: "FM", flag: "🇫🇲", currency: "USD", symbol: "$" },
    { name: "Moldova, Republic of", code: "MD", flag: "🇲🇩", currency: "MDL", symbol: "L" },
    { name: "Monaco", code: "MC", flag: "🇲🇨", currency: "EUR", symbol: "€" },
    { name: "Mongolia", code: "MN", flag: "🇲🇳", currency: "MNT", symbol: "₮" },
    { name: "Montserrat", code: "MS", flag: "🇲🇸", currency: "XCD", symbol: "$" },
    { name: "Morocco", code: "MA", flag: "🇲🇦", currency: "MAD", symbol: "DH" },
    { name: "Mozambique", code: "MZ", flag: "🇲🇿", currency: "MZN", symbol: "MT" },
    { name: "Myanmar", code: "MM", flag: "🇲🇲", currency: "MMK", symbol: "K" },
    { name: "Namibia", code: "NA", flag: "🇳🇦", currency: "NAD", symbol: "$" },
    { name: "Nauru", code: "NR", flag: "🇳🇷", currency: "AUD", symbol: "$" },
    { name: "Nepal", code: "NP", flag: "🇳🇵", currency: "NPR", symbol: "₨" },
    { name: "Netherlands", code: "NL", flag: "🇳🇱", currency: "EUR", symbol: "€" },
    { name: "Netherlands Antilles", code: "AN", flag: "🇦🇳", currency: "ANG", symbol: "ƒ" },
    { name: "New Caledonia", code: "NC", flag: "🇳🇨", currency: "XPF", symbol: "₣" },
    { name: "New Zealand", code: "NZ", flag: "🇳🇿", currency: "NZD", symbol: "$" },
    { name: "Nicaragua", code: "NI", flag: "🇳🇮", currency: "NIO", symbol: "C$" },
    { name: "Niger", code: "NE", flag: "🇳🇪", currency: "XOF", symbol: "CFA" },
    { name: "Nigeria", code: "NG", flag: "🇳🇬", currency: "NGN", symbol: "₦" },
    { name: "Niue", code: "NU", flag: "🇳🇺", currency: "NZD", symbol: "$" },
    { name: "Norfolk Island", code: "NF", flag: "🇳🇫", currency: "AUD", symbol: "$" },
    { name: "Northern Mariana Islands", code: "MP", flag: "🇲🇵", currency: "USD", symbol: "$" },
    { name: "Norway", code: "NO", flag: "🇳🇴", currency: "NOK", symbol: "kr" },
    { name: "Oman", code: "OM", flag: "🇴🇲", currency: "OMR", symbol: "﷼" },
    { name: "Pakistan", code: "PK", flag: "🇵🇰", currency: "PKR", symbol: "₨" },
    { name: "Palau", code: "PW", flag: "🇵🇼", currency: "USD", symbol: "$" },
    { name: "Palestinian Territory, Occupied", code: "PS", flag: "🇵🇸", currency: "ILS", symbol: "₪" },
    { name: "Panama", code: "PA", flag: "🇵🇦", currency: "PAB", symbol: "B/." },
    { name: "Papua New Guinea", code: "PG", flag: "🇵🇬", currency: "PGK", symbol: "K" },
    { name: "Paraguay", code: "PY", flag: "🇵🇾", currency: "PYG", symbol: "₲" },
    { name: "Peru", code: "PE", flag: "🇵🇪", currency: "PEN", symbol: "S/." },
    { name: "Philippines", code: "PH", flag: "🇵🇭", currency: "PHP", symbol: "₱" },
    { name: "Pitcairn", code: "PN", flag: "🇵🇳", currency: "NZD", symbol: "$" },
    { name: "Poland", code: "PL", flag: "🇵🇱", currency: "PLN", symbol: "zł" },
    { name: "Portugal", code: "PT", flag: "🇵🇹", currency: "EUR", symbol: "€" },
    { name: "Puerto Rico", code: "PR", flag: "🇵🇷", currency: "USD", symbol: "$" },
    { name: "Qatar", code: "QA", flag: "🇶🇦", currency: "QAR", symbol: "﷼" },
    { name: "Reunion", code: "RE", flag: "🇷🇪", currency: "EUR", symbol: "€" },
    { name: "Romania", code: "RO", flag: "🇷🇴", currency: "RON", symbol: "lei" },
    { name: "Russian Federation", code: "RU", flag: "🇷🇺", currency: "RUB", symbol: "₽" },
    { name: "Rwanda", code: "RW", flag: "🇷🇼", currency: "RWF", symbol: "R₣" },
    { name: "Saint Helena", code: "SH", flag: "🇸🇭", currency: "SHP", symbol: "£" },
    { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", currency: "XCD", symbol: "$" },
    { name: "Saint Lucia", code: "LC", flag: "🇱🇨", currency: "XCD", symbol: "$" },
    { name: "Saint Pierre and Miquelon", code: "PM", flag: "🇵🇲", currency: "EUR", symbol: "€" },
    { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", currency: "XCD", symbol: "$" },
    { name: "Samoa", code: "WS", flag: "🇼🇸", currency: "WST", symbol: "T" },
    { name: "San Marino", code: "SM", flag: "🇸🇲", currency: "EUR", symbol: "€" },
    { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", currency: "STD", symbol: "Db" },
    { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", currency: "SAR", symbol: "﷼" },
    { name: "Senegal", code: "SN", flag: "🇸🇳", currency: "XOF", symbol: "CFA" },
    { name: "Serbia and Montenegro", code: "CS", flag: "🇷🇸", currency: "RSD", symbol: "Дин." },
    { name: "Seychelles", code: "SC", flag: "🇸🇨", currency: "SCR", symbol: "₨" },
    { name: "Sierra Leone", code: "SL", flag: "🇸🇱", currency: "SLL", symbol: "Le" },
    { name: "Singapore", code: "SG", flag: "🇸🇬", currency: "SGD", symbol: "$" },
    { name: "Slovakia", code: "SK", flag: "🇸🇰", currency: "EUR", symbol: "€" },
    { name: "Slovenia", code: "SI", flag: "🇸🇮", currency: "EUR", symbol: "€" },
    { name: "Solomon Islands", code: "SB", flag: "🇸🇧", currency: "SBD", symbol: "$" },
    { name: "Somalia", code: "SO", flag: "🇸🇴", currency: "SOS", symbol: "S" },
    { name: "South Africa", code: "ZA", flag: "🇿🇦", currency: "ZAR", symbol: "R" },
    { name: "South Georgia and the South Sandwich Islands", code: "GS", flag: "🇬🇸", currency: "GBP", symbol: "£" },
    { name: "Spain", code: "ES", flag: "🇪🇸", currency: "EUR", symbol: "€" },
    { name: "Sri Lanka", code: "LK", flag: "🇱🇰", currency: "LKR", symbol: "₨" },
    { name: "Sudan", code: "SD", flag: "🇸🇩", currency: "SDG", symbol: "ج.س." },
    { name: "Suriname", code: "SR", flag: "🇸🇷", currency: "SRD", symbol: "$" },
    { name: "Svalbard and Jan Mayen", code: "SJ", flag: "🇸🇯", currency: "NOK", symbol: "kr" },
    { name: "Swaziland", code: "SZ", flag: "🇸🇿", currency: "SZL", symbol: "L" },
    { name: "Sweden", code: "SE", flag: "🇸🇪", currency: "SEK", symbol: "kr" },
    { name: "Switzerland", code: "CH", flag: "🇨🇭", currency: "CHF", symbol: "CHF" },
    { name: "Syrian Arab Republic", code: "SY", flag: "🇸🇾", currency: "SYP", symbol: "£" },
    { name: "Taiwan, Province of China", code: "TW", flag: "🇹🇼", currency: "TWD", symbol: "NT$" },
    { name: "Tajikistan", code: "TJ", flag: "🇹🇯", currency: "TJS", symbol: "SM" },
    { name: "Tanzania, United Republic of", code: "TZ", flag: "🇹🇿", currency: "TZS", symbol: "TSh" },
    { name: "Thailand", code: "TH", flag: "🇹🇭", currency: "THB", symbol: "฿" },
    { name: "Timor-Leste", code: "TL", flag: "🇹🇱", currency: "USD", symbol: "$" },
    { name: "Togo", code: "TG", flag: "🇹🇬", currency: "XOF", symbol: "CFA" },
    { name: "Tokelau", code: "TK", flag: "🇹🇰", currency: "NZD", symbol: "$" },
    { name: "Tonga", code: "TO", flag: "🇹🇴", currency: "TOP", symbol: "T$" },
    { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", currency: "TTD", symbol: "TT$" },
    { name: "Tunisia", code: "TN", flag: "🇹🇳", currency: "TND", symbol: "DT" },
    { name: "Turkey", code: "TR", flag: "🇹🇷", currency: "TRY", symbol: "₺" },
    { name: "Turkmenistan", code: "TM", flag: "🇹🇲", currency: "TMT", symbol: "m" },
    { name: "Turks and Caicos Islands", code: "TC", flag: "🇹🇨", currency: "USD", symbol: "$" },
    { name: "Tuvalu", code: "TV", flag: "🇹🇻", currency: "AUD", symbol: "$" },
    { name: "Uganda", code: "UG", flag: "🇺🇬", currency: "UGX", symbol: "USh" },
    { name: "Ukraine", code: "UA", flag: "🇺🇦", currency: "UAH", symbol: "₴" },
    { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", currency: "AED", symbol: "د.إ" },
    { name: "United Kingdom", code: "GB", flag: "🇬🇧", currency: "GBP", symbol: "£" },
    { name: "United States", code: "US", flag: "🇺🇸", currency: "USD", symbol: "$" },
    { name: "United States Minor Outlying Islands", code: "UM", flag: "🇺🇲", currency: "USD", symbol: "$" },
    { name: "Uruguay", code: "UY", flag: "🇺🇾", currency: "UYU", symbol: "$U" },
    { name: "Uzbekistan", code: "UZ", flag: "🇺🇿", currency: "UZS", symbol: "лв" },
    { name: "Vanuatu", code: "VU", flag: "🇻🇺", currency: "VUV", symbol: "VT" },
    { name: "Venezuela", code: "VE", flag: "🇻🇪", currency: "VEF", symbol: "Bs" },
    { name: "Vietnam", code: "VN", flag: "🇻🇳", currency: "VND", symbol: "₫" },
    { name: "Virgin Islands, British", code: "VG", flag: "🇻🇬", currency: "USD", symbol: "$" },
    { name: "Virgin Islands, U.S.", code: "VI", flag: "🇻🇮", currency: "USD", symbol: "$" },
    { name: "Wallis and Futuna", code: "WF", flag: "🇼🇫", currency: "XPF", symbol: "₣" },
    { name: "Western Sahara", code: "EH", flag: "🇪🇭", currency: "MAD", symbol: "DH" },
    { name: "Yemen", code: "YE", flag: "🇾🇪", currency: "YER", symbol: "﷼" },
    { name: "Zambia", code: "ZM", flag: "🇿🇲", currency: "ZMW", symbol: "ZK" },
    { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", currency: "ZWL", symbol: "$" }
];
